//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp15
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public Customers()
        {
            //this.Orders = new List<Orders>();
        }
    
        //te 3 bede w glownej tabeli tylko
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }

        //te bede w dodatkowym oknie


        public System.DateTime LastOrder { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int OrdersAmountValue { get; set; }
        public int OrdersCount { get; set; }
        public int OrdersId { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
