//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp15
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int Id { get; set; }
        public int Quantity { get; set; }
        public decimal UPrice { get; set; }
        public decimal TotPrice { get; set; }
        public int ProducterId { get; set; }
        public int UserssID { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
