//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp15
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public int NumberOfProducts { get; set; }
        public int OrderId { get; set; }
        public int CustomerssID { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Customers Customers { get; set; } = null;
        public virtual Orders Orders { get; set; }

        public Products()
        {
            
        }
    }
}
